packages:
  - "apps/*"
  - "servers/*"
  - "packages/*"
  - "prebuilt/*"
  - "prebuilt/*/*"

allowBuilds:
  esbuild: true
  unrs-resolver: true

audit:
  level: high

overrides:
  "@next/eslint-plugin-next>fast-glob": "workspace:@workspace/fast-glob-compat@*"
  "@ts-morph/common>fast-glob": "workspace:@workspace/fast-glob-compat@*"
  "shadcn>fast-glob": "workspace:@workspace/fast-glob-compat@*"
